### ISSUE TITLE
XHR requests time out even though jQuery ajaxSettings timeout is set to higher value

### ISSUE THREAD

**Issue by ByteDoc** [globules-io/cordova-plugin-ios-xhr#11]
**Description**
Ajax call (with long server processing time), done via jQuery, has timeout set to value higher than 60 seconds.
Request times out after 60 seconds, unfinished, resulting in ajax error.
Timeout value in ajax settings is not respected in the plugin.

**Preferences**
```
<preference name="NativeXHRLogging" value="full" />
<preference name="AllowUntrustedCerts" value="true" />
<preference name="InterceptRemoteRequests" value="all" />
<preference name="allowFileAccessFromFileURLs" value="true" />
<preference name="allowUniversalAccessFromFileURLs" value="true" />
```

**Expected behavior**
When using $.ajaxSettings.timeout of e.g. 180000, I expect the network request to only err/timeout after 180 seconds, not earlier.

**Device**
 - Device: iPad
 - OS: iOS 14.2
 - Browser: WKWebView
 - Hybrid app: Cordova build, using VoltBuilder

**Example call**
```
$.ajax({
  type: "POST",
  contentType: "application/json",
  url: "url_to_server_endpoint",
  dataType: "json",
  timeout: 180000,
  data: encodeURIComponent("someJSONdata"),
  success: function (data) {
    // ...
  },
  error: function(result,status,errorThrown) {
    // ...
  }
});
```

**Comment by globules-io** [comment]
The max timeout for a XMLHttpRequest in Safari & Chrome is 60 seconds.

**Comment by ByteDoc** [comment]
Sorry, can't confirm this, longer timeouts are possible as well.

Following test:
Running cordova app on iPad, debugging in Safari on Mac.
Breaking at this line ...
https://github.com/globules-io/cordova-plugin-ios-xhr/blob/f1352921ac71d9e19da511d0db0c39be90bb15ab/src/www/ios/xhr-polyfill.js#L603
... and setting timeoutInSecs to 100 manually in console.
I'm then halting the server code with server-side breakpoints.
- If I halt the server code for more than 100 seconds, then the request in the app ends with timeout.
- If I halt the server code for anything between 60 and 100 seconds, and continue this way, the request ends successfully, XHR response is received.
