### ISSUE TITLE
BUG: getWebContentResourceURL: has fixed baseURL as mainBundle resourceURL

### ISSUE THREAD

**Issue by vfranchi** [globules-io/cordova-plugin-ios-xhr#13]
**Describe the bug**
If you change the initial cordova page to something other than "index.html" the plugin won't load relative path file:// resources correctly. It always tries to resolve relative URL resources from the `www/` cordova folder. So, for example, if I have this directory tree for my app

www/
--foo/
----index.html
----script.js

When trying to load relative URL as `script.js` the plugin will resolve URL to be `file://<all bundle IDs and Application IDs>/www/script.js` and will return a 404 File Not Found error.

**Paste your preferences**

    
    <content src="foo/index.html" />
    <preference name="allowFileAccessFromFileURLs" value="true" />
    <preference name="allowUniversalAccessFromFileURLs" value="true" />

**Expected behavior**
Method `-(NSURL*)getWebContentResourceURL: (NSString*) uri` from `CDVWKWebViewFileXhr.m` should resolve a relative URL `script.js` as `www/foo/script.js`

**Additional context**
Fixed the problem by changing lines 170 and 171 from mentioned method to

    NSURL *baseURL = [[(WKWebView *)self.webView URL] URLByDeletingLastPathComponent];
    NSString *wwwuri = uri;

This way, relative resources URL are always resolved from the current WKWebView location.

**Comment by globules-io** [comment]
Pull request are encouraged...

**Comment by globules-io** [comment]
Will be pushed in 1.2.0
