### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by vprabusiva** [globules-io/cordova-plugin-ios-xhr#15]
Hi, 

While Install this plugin I got below issue.

cordova plugin add @globules-io/cordova-plugin-ios-xhr
Failed to fetch plugin cordova-plugin-ios-xhr via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: cordova-plugin-ios-xhr@latest

npm ERR! A complete log of this run can be found in:

**Comment by globules-io** [comment]
There is no "latest". Use a version number.

**Comment by vprabusiva** [comment]
.I tried below commands Still getting same error. thanks

>>> cordova plugin add @globules-io/cordova-plugin-ios-xhr@1.1.0

>>> cordova plugin add https://github.com/globules-io/cordova-plugin-ios-xhr



Failed to fetch plugin cordova-plugin-ios-xhr via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: cordova-plugin-ios-xhr@latest

npm ERR! A complete log of this run can be found in:

**Comment by csantanu** [comment]
Facing same issue using - cordova plugin add @globules-io/cordova-plugin-ios-xhr@1.1.0

Failed to fetch plugin cordova-plugin-ios-xhr via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cordova-plugin-ios-xhr - Not found
npm ERR! 404
npm ERR! 404  'cordova-plugin-ios-xhr@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by csantanu** [comment]
Same problem with - cordova plugin add @globules-io/cordova-plugin-ios-xhr@1.2.0

**Comment by faugusztin** [comment]
Which Cordova version are you using ? If i remember correctly, older versions of Cordova (9 and before) can't handle namespaced NPM packages as plugins, and they try to download non-namespaced version as well. With Cordova 10 it should work.

Note how it tries to download "https://registry.npmjs.org/cordova-plugin-ios-xhr", without the globules namespace.

**Comment by globules-io** [comment]
Cordova 10

**Comment by vprabusiva** [comment]
Thanks for your reply, I am using Cordova 9.

**Comment by souly1** [comment]
same, cannot install :/

**Comment by globules-io** [comment]
Try from config.xml

`<plugin name="@globules-io/cordova-plugin-ios-xhr" spec="^1.2.0" />`

**Comment by souly1** [comment]
And then do what? ```plugin add``` ? ```platform rm/add iOS``` ?

**Comment by globules-io** [comment]
This is not a cordova support forum.

**Comment by souly1** [comment]
😂😂
This is not a plugin worth digging for something I had no need for in the past 5 years with Cordova.
Already managed.

Thanks
