### ISSUE TITLE
Issue with post ajax request and request at startup

### ISSUE THREAD

**Issue by neoCobol** [globules-io/cordova-plugin-ios-xhr#2]
Hello,

When I'm using this plugin with ajax request, the "async=false" parameter does not work, the program continue in next functions before came back in response of the request.
Of course I want to wait for the response of request before executing next functions in my code.

Also when I'm doing request at startup of my application, the error fixed by this plugin is present.

Thank you for your time,
neoCobol

**Comment by globules-io** [comment]
unrelated to plugin
