### ISSUE TITLE
Not loading local files

### ISSUE THREAD

**Issue by spreadzz** [globules-io/cordova-plugin-ios-xhr#3]
This plugin is not working for me.

I understand this was done as a fix for cordova-plugin-wkwebview-file-xhr which worked ok for my app, until cordova-ios 6

My app loads the html and js files using JS and ajax, but they are not working.

Am I doing something wrong or?

**Comment by globules-io** [comment]
Yes, most probably. Please be more specific than "not working". Also paste your preferences.

**Comment by spreadzz** [comment]
By not working, I mean it's not loading the local HTML and JS files with XMLHTTPRQUEST.
It's the same as I never install the plugin. And it's the same as before I started using cordova-plugin-wkwebview-file-xhr

I do not get any errors in the console. I hooked the xCode with Safari to check out.
I'm not sure what more info I can provide you.

If I downgrade to cordova-ios 5.1.1
Install cordova-plugin-wkwebview-file-xhr and it's dependencies it works.
But unfortunately I need cordova-ios 6

So right now my app is stuck at a gray blank screen because it can not load the necessary local files.

<img width="450" alt="Screenshot 2020-08-10 at 15 06 53" src="https://user-images.githubusercontent.com/7011668/89781248-a3fba780-db1b-11ea-86e2-85c8d880e844.png">


<preference name="target-device" value="universal" />
<preference name="deployment-target" value="11.0" />
<preference name="SuppressesLongPressGesture" value="true" />
<preference name="DisallowOverscroll" value="true" />
<preference name="WKWebViewOnly" value="true" />
<feature name="CDVWKWebViewEngine">
   <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />

**Comment by spreadzz** [comment]
```
        <preference name="target-device" value="universal" />
        <preference name="deployment-target" value="11.0" />
        <preference name="SuppressesLongPressGesture" value="true" />
        <preference name="DisallowOverscroll" value="true" />
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

**Comment by globules-io** [comment]
1. There is no preference for this plugin
2. 

```
 <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```
is obsolete with cordova-ios.

Please RTFM
