### ISSUE TITLE
BUG plugin leaves junk in package.json after uninstall

### ISSUE THREAD

**Issue by svenemtell** [globules-io/cordova-plugin-ios-xhr#6]
**Describe the bug**
After uninstalling using `cordova plugin rm cordova-plugin-ios-xhr` the following is left in package.json

```
    "devDependencies": {
        "@globules-io/cordova-plugin-ios-xhr": "^1.0.5",
```

**Expected behavior**
Not leaving anything in package.json after uninstall.

**Desktop (please complete the following information):**
 My environment:
```
node 10.22
npm 6.14.6
cordova 10.0.0
cordova-ios 6.1.0
ios-deploy 1.11.0
```

**Additional context**
Somewhat connected with #4.

**Comment by globules-io** [comment]
Fixed. Please do a PR next time.

**Comment by svenemtell** [comment]
> Fixed. Please do a PR next time.

Ok, thanks!
