### ISSUE TITLE
Is there an url length limit?

### ISSUE THREAD

**Issue by Risingson** [globules-io/cordova-plugin-ios-xhr#7]
**Describe the bug**
I get an error on a xhr call to a long url with a length of 761 characters.

**Paste your preferences**
trying to fetch

https://esi.evetech.net/v1/route/30000142/30000125/?flag=shortest&connections=31000005|30004615,30004615|31000005,31000005|30000616,30000616|31000005,31000005|30004321,30004321|31000005,31000005|30001304,30001304|31000005,31000005|31000154,31000154|31000005,31000005|30004060,30004060|31000005,31000005|30001644,30001644|31000005,31000005|30004606,30004606|31000005,31000005|30005034,30005034|31000005,31000005|30005225,30005225|31000005,31000005|31000916,31000916|31000005,31000005|31001100,31001100|31000005,31000005|31001562,31001562|31000005,31000005|30002812,30002812|31000005,31000005|31001183,31001183|31000005,31000005|31001685,31001685|31000005,31000005|30005306,30005306|31000005,31000005|31000783,31000783|31000005,31000005|30004109,30004109|31000005

but getting a {"readyState":4,"status":400,"statusText":"Bad Request"} error.
network console shows that no xhr call has been made 

**Expected behavior**
xhr response should be: [30000142,30000140,30000119,30000125]
If it is url length then there should be no limit.

**Smartphone (please complete the following information):**
iOS 13.6

**Comment by globules-io** [comment]
Paste your preferences To make sure you've set the plugin
https://github.com/globules-io/cordova-plugin-ios-xhr/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Risingson** [comment]
excerpt from package.json
  "devDependencies": {
    "@globules-io/cordova-plugin-ios-xhr": "^1.0.8",
    "cordova-ios": "^6.1.0"
  },

**Comment by globules-io** [comment]
You should escape your pipes with %7C btw,

**Comment by Risingson** [comment]
I unfortunately cannot try right now. Is that the reason it is not working or is it just a sanitizing hint :) ?

**Comment by globules-io** [comment]
https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters

**Comment by Risingson** [comment]
Thank you very much for your time.
