### ISSUE TITLE
Plugin doesnt work on iOS 14

### ISSUE THREAD

**Issue by martijnmichel** [globules-io/cordova-plugin-ios-xhr#8]
As stated in topic, updating to iOS 14 broke loading files via this plugin. On iOS 13.x everything worked.

**Comment by globules-io** [comment]
iOS14 is still in beta and full of bugs. Closing for now.

**Comment by globules-io** [comment]
Reopening to keep on eye an it

**Comment by globules-io** [comment]
Meanwhile if you have any logs, that would be appreciated
